# Generated by Django 2.2.2 on 2019-07-28 07:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190728_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 28, 7, 50, 32, 478673, tzinfo=utc)),
        ),
    ]
