# Generated by Django 2.2.3 on 2019-07-29 06:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190728_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 29, 6, 44, 5, 459870, tzinfo=utc)),
        ),
    ]
