# Generated by Django 2.2.3 on 2019-07-29 07:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190729_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 29, 7, 32, 4, 539215, tzinfo=utc)),
        ),
    ]
