# Generated by Django 2.2.3 on 2019-07-29 09:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190729_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 29, 9, 41, 20, 952633, tzinfo=utc)),
        ),
    ]
