# Generated by Django 2.2.3 on 2019-07-30 09:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20190729_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 30, 9, 54, 4, 112384, tzinfo=utc)),
        ),
    ]
