# Generated by Django 2.2.3 on 2019-07-30 10:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20190730_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 30, 10, 18, 13, 551545, tzinfo=utc)),
        ),
    ]
