# Generated by Django 2.2.2 on 2019-07-30 10:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20190730_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 30, 10, 47, 37, 684529, tzinfo=utc)),
        ),
    ]
