# Generated by Django 2.2.2 on 2019-07-30 10:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20190730_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 30, 10, 51, 43, 850713, tzinfo=utc)),
        ),
    ]
